### PR TITLE
Initial Zaptec template

### PR DESCRIPTION
**Pull request by aunefyren**
Hello, this is an initial template for the Zaptec electric charger. I managed to do some testing, so it is functional, but it needs more love to be perfect. My problem at this point is that I am not fully sure of how every configuration in the template works, and I am not that experienced with the charger yet.

I have encouraged others in the Zaptec development repository to contribute: https://github.com/custom-components/zaptec/issues/82

### CODE REVIEW

**Comment by tmjo** [comment]
Sounds good! I'll take a look at it. Could you send me some examples of the Zaptec entity names?

**Comment by aunefyren** [comment]
Sure! not entirely sure how to do that in a way that benefits you, but here are the ones listed when clicking on the integration:

image

And here is the device:

image

And here are the entity states, tried to quickly remove information that could be sensetive:

zaptec ent

**Comment by tmjo** [comment]
Thanks, that should do it. It is just for me to have a better understanding when I test it (without actually having the charger) and see if the template looks ok.

**Comment by sveinse** [comment]
> I see some are prefixed with your name (assuming that's a name you have given your account or charger) and others with "zapteccharger_". Do you know why there is this difference?

(Maintainer for the Zaptec integration here)

Both the entity name and the entity id are based on the name the user has set for the device in the charger cloud. So if the user has named the charger for "My Charger", the entities will be named "My Charger *" and `sensor.my_charger_*`. E.g. "My Charger Charge Power" for name and "sensor.my_charger_charge_power" for ID. All entities have unique IDs which is immutable from the user set name, making it safe to rename the charger.

**Comment by aunefyren** [comment]
Nydelig folkens

**Comment by tmjo** [comment]
That sounds good and is what the card "expects" too. I'll take a look.

**Comment by tmjo** [comment]
Sorry for the delay, I'll see if I can merge asap.

**Comment by VanHynten** [comment]
Any Updates?

**Comment by VanHynten** [comment]
Thanks for the merge, is it possible to release a new release, unfortunately I have no idea how to "build" one myself.

**Comment by tmjo** [comment]
It will come, I have some issues with npm so I couldn't compile this weekend.

**Comment by tmjo** [comment]
Sorry for the delay. Finally released beta version v0.2.8a with this included. Please test and report. Will be released generally if it seems to work well.

PS! You need to enable beta-version for the card in HACS to test (click re-download and switch on beta versions if you didn't already).

**Pull request merged**
